name: bwc_edu
values:
  - key: admin_token
    value: ''
  - key: courseId
    value: ''
  - key: student_token
    value: ''
  - key: rec_id
    value: ''
  - key: damu
    value: ''
  - key: exam_id
    value: ''
  - key: cert_id
    value: ''
